rvm:
  - 1.9.3
bundler_args: --without development
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "rake clean"
script: "rake upload_latest"
env: {secure: ARFGZqoOep+0J6J1AJRJnR3AjZ6Xw2tfMGQUZggvmixlovpmIZdwNe3HMtP/pnC+vakufHo91zD1Ul2UKVfl562PahWYzfJhw9HHmHpQI6v9bBmfa83eSuBKG0WE/+lhy0SIviUWdWkiYdpVnJ9O3fAJnsVVik+LuHAhcQy8GmM=}